### ISSUE TITLE
PD-Modal + PD-Dropdown

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#100]
We have another case of the Dropdown not working in a modal. Feel free to send us a debug build for some console.logs and we can further investigate this issue.

Our setup right now is:
pd-panel -> pd-panel-content -> Button that opens a Modal -> pd-modal with pd-dropdown

The Confirm/Cancel buttons work and the dropdown content is visible in the DOM

**Comment by matthiasbaldi** [comment]
Do you mean something like this?
That should work in the current master branch.

![modal_with_dropdown](https://user-images.githubusercontent.com/12791996/142624831-8ad73631-7ae4-4c9d-8076-ff6df9d77932.gif)

I will let this issue open to track it, if you have the issue also in the 1.8.0 release, which we will release soon.

**Comment by thomasschneiter** [comment]
@CuriaPLUS I've added some console.log to the dropdown in 1.8.1. We're using the composedPath() of the clicked element to check if a 'pd-dropdown' was clicked and if it should be closed or not.

Can you click the dropdown in question and check the console.log with 'PD-DROPDOWN (ComposedPath)'. It should contain a pd-dropdown in it's list. If it's not in the list, it could lead to the dropdown being opened and immediately closed again.

 The other console logs show the current state of the dropdown (open/close)

Be aware that this is executed for all the dropdowns on the page, so there are logs for all of them.

**Comment by CuriaPLUS** [comment]
Hey we updated to 1.8.1 and the Dropdowns seem to work. From what I could see it must have been a change in between the different 1.8.0 releases. You can disabled to console.logs again for the next release. Thanks a lot!
