### ISSUE TITLE
PD-Panel-Header Click

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#101]
As shown this week in our meeting we are trying to add more actions to a panel.
Adding the icon works like a charm but at the moment there is no way to prevent the click on the header to toggle the collapse on/off -> if we have an additional Icon in the header we would like to prevent the collapse to be called. 

Is there a way to prevent bubbling of this event?

Edit: Furthermore if the prop collapsable is set to false the header still handles the click on collapses/expands

This would be rather urgent ;)

- [x] collapsible fix (in 1.8.0 release)
- [x] additional icons (in 1.8.1 release)

**Comment by matthiasbaldi** [comment]
Short question to the second point for the additional icons: Do you only want to block the event on a click directly on the icon or do you want to block the click events on the complete header?
This was not 100% clear to me.

**Comment by CuriaPLUS** [comment]
I will add an example on Monday. UXwise I am not sure what is better. I could see it as an option or you guys decide whats best for other users of the Library

**Comment by matthiasbaldi** [comment]
Ty for the answer.
Yea, what do you think? Do you open the panel programmatically or do you want to still open it directly via the click event?
I think this is the required question. Because when I block the click event on the complete header you have to open the panel yourself. If you don't want to do that, I only block the event on the icon, or may you have to block it there yourself - I have to analyze this part.

**Comment by CuriaPLUS** [comment]
```
<pd-panel-header slot="header">
        <div class="header">
          Notizen
          <pd-icon name="link" size="1.5" @click="expand"/>
        </div>
      </pd-panel-header>
```

This is how we are adding more icons. I feel UXwise its better if the user can click on the header as well as on the icon to expand the panel

**Comment by CuriaPLUS** [comment]
I just saw that the collapsible is not synced on change so if its set to a dynamic boolean and that changes the panel keeps the function (should be reactive)

**Comment by thomasschneiter** [comment]
@CuriaPLUS Do you "overwrite" the collabsible icon this way? Changing 'collapsed' only works if 'collapsible' attr is set, but this also shows the icon.

**Comment by CuriaPLUS** [comment]
If we don't show the icon we expect the panel to be open but depending on some other logic this can change. We want to guide the user with the help of the panels and depending on the state some panels can be collapsed or are forced to be open
