### ISSUE TITLE
PD-Search, PD-Dropdown & PD-Combobox width

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#103]
We have some views where we are using either of those elements and they seem to stop scaling below a certain width (see screenshot
![Screenshot 2021-11-18 at 13 12 22](https://user-images.githubusercontent.com/77280472/142413247-0b0a5a6e-819d-44cc-8e71-8765c0f147be.png)

The parent they are in has
```
flex: 0 0 25%;
max-width: 25%;
```

**Comment by thomasschneiter** [comment]
This is given by the `<input>` [size](https://www.w3schools.com/tags/att_input_size.asp) attribute which is `20` by default (I think ~100px initial width depending on the browser). 

I'll set this to default '1' and add a `size` Prop to "pd-checkbox", "pd-search" and "pd-datepicker" to overwrite it.

pd-dropdown should not have this issue.
