### ISSUE TITLE
pd-datepicker events

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#123]
Please see the attached video from [the Storybook](https://parlamentsdienstecore.app.lambda-it.ch/?path=/story/forms-inputs-datepicker--datepicker&args=config_allow_input:true) as an illustration for the following points.

1. Starting from the empty state, a date is selected and an event `pd-value-update` is sent correctly.
1. Then the calendar overlay is opened and closed without a change of the date. However, there is an event `pd-value-update` sent, which is **not expected** to happen since the value didn't change.
1. Then the selected date in `pd-datepicker` is cleared (via keyboard delete/backspace). There is no event `pd-value-update` sent, which **would be expected** since the value changed.

https://user-images.githubusercontent.com/77280472/151501868-fd82c3e5-c0e1-40bc-9d39-b26ac0ab0224.mov

### Not in the video but related
We thought of using the event `pd-change` instead (although the semantic meaning of `pd-value-update` fits better), because `pd-change` is sent when the date is emptied. However, there seems to be another problem with `pd-change`.

When we prepare a datepicker with a preselected `date` and listen on `pd-change` like so ...
```
<pd-datepicker :date="2022-01-10" @pd-change="onChangeDate($evt)" />
```
... we receive an event `pd-change` immediately after the component is mounted. This is **not expected** since the date didn't change but was just set up initially.

If you could improve these points, this would make the event handling with `pd-datepicker` more comfortable. Thanks!

**Comment by thomasschneiter** [comment]
@CuriaPLUS We just emit the default wrapped flatpicker events, there is not much we can change for them. The events are documented [here](https://flatpickr.js.org/events/)

**But** previously `pd-change` emitted the wrapped pd-input change event. I've changed this so pd-change now also emits the default flatpicker `onChange` event. The initial `setDate `should not emit in this case.
