### ISSUE TITLE
Clickable Listelement

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#125]
In some cases, it would make great sense to be able to make the various list (i.e. https://parlamentsdienstecore.app.lambda-it.ch/?path=/story/interactions-list--expandable-list) clickable. For example to open a "Geschäft" in the Arbeitsvorrat.  Currently we are limited in what we can make clickable and what not, which is not ideal from a UX perspective. 

- "Content Area" of the line (from left to right everything up until the action menu) would be one clickable area.
- Action Menu a separate one
- Would also include a respective hover effect. 

![clickable line element](https://user-images.githubusercontent.com/77280472/153445045-11896344-7b5a-46c7-acfe-6e717b09cf27.jpg)

**Comment by thomasschneiter** [comment]
I've added a `content-click` property to enable this feature for `pd-list-item-expandable`. If enabled, a `pd-content-click` event is emitted on click (status + content slot) and a hover effect is visible. Hover color can be changed with `--pd-list-item-content-hover` css var.

Check storybook for [example](http://localhost:50874/?path=/story/interactions-list--expandable-list&args=contentClick:true)
