### ISSUE TITLE
PD-Panel new prop for Padding

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#129]
we need a prop to control the padding of the PD-Panel-Content so we can reuse this component also with the new design enhancements from design sensor. 
So we can create both like this:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/77280472/155288436-ed847d93-e018-4154-94fc-a417d296769f.png">
and this
<img width="385" alt="image" src="https://user-images.githubusercontent.com/77280472/155288483-a03477bf-9e55-4924-9a7a-78318984e779.png">

**Comment by thomasschneiter** [comment]
@CuriaPLUS  pd-panel-content already has a css var `var(--pd-panel-content-padding, 1.25rem)` that you can use to modify/remove the padding of the content.

**Comment by CuriaPLUS** [comment]
@thomasschneiter works fine for us :)
