### ISSUE TITLE
pd-radio causes positioning issues in Firefox

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#132]
We use the pd-radio component in an expandable item list. So the item content is shown after a expand action. The Issue here is now that the inner label of the pd-radio component is positioned absolute so it stays at the place at it will be rendered when the item is expanded. This behaviour causes empty space at the end of the list and a scrollbar in some Firefox versions.

From our view the absolute behaviour is not needed at all or at least should be wrapped in a relative context within the component itself (see possible solution).

Issue:
<img width="1777" alt="image" src="https://user-images.githubusercontent.com/77280472/157260956-9ce255f5-ea63-438e-b8d6-54fcc27d49bb.png">

Possible Solution:
<img width="1776" alt="image" src="https://user-images.githubusercontent.com/77280472/157261244-1c6f12a3-e796-43ed-9efe-b9f3ded68376.png">

Can be reproduced in some Firefox versions. My Setup is following:
- macOS Big Sur V 11.6
- Firefox 92.0 (64Bit)

**Comment by thomasschneiter** [comment]
I was not able to reproduce this issue in firefox.

This styling was used to visually hide the <input> element similar to [this](https://www.accessibility-developer-guide.com/examples/hiding-elements/visually/). 
I'll improve the visually-hidden style in the next release v2.3.1 to this:

`position: absolute;
    width: 1px;
    height: 1px;
    overflow: hidden;
    clip: rect(0 0 0 0);
    -webkit-clip-path: inset(0 0 0 0);
    clip-path: inset(0 0 0 0);
    margin: -1px;
    padding: 0;
    border: 0;
`

The relative position on the component is not needed in my opinion as the hidden element doesn't have a actual size.
