### ISSUE TITLE
Storybook update

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#133]
The storybook doesn't seem to have been updated recently. Would it be possible to release the newest version? It's helpful for our non-devs. Thank you.

**Comment by thomasschneiter** [comment]
You probably still use the old link
https://parlamentsdienstecore.lambda-it.ch
instead of
https://parlamentsdienstecore.app.lambda-it.ch

If that's the case please switch to the new one.
