### ISSUE TITLE
Hide Placeholders in inputs when disabled or readonly

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#136]
Currently when you disable an Input element the Placeholder is still shown. 
![image](https://user-images.githubusercontent.com/77280472/159663497-a5481301-7d09-49bc-bc28-b1e750e66513.png)
This could lead to some confusion if a field is set when viewing them in the readonly mode. This is why we suggest to hide the placeholder when the input is disabled or readonly

**Comment by thomasschneiter** [comment]
This is default html input behaviour, I don't think we should change that. @MadeleineMatter what do you think?

**Comment by MadeleineMatter** [comment]
@thomasschneiter @CuriaPLUS If you take a look at the designsystem, the disabled state should look quite different from the read only state https://xd.adobe.com/view/9749c3e8-0f7c-4f56-7f39-c3dc9c25444b-e178/screen/b6fece0c-38e1-4f10-8a12-6ea08d2a05f1/.
Or did I get your question wrong?

**Comment by MadeleineMatter** [comment]
Update for the disabled and read only states
https://xd.adobe.com/view/4b788182-140b-46ff-46f5-3c623cf5b5b3-3d49/screen/b6fece0c-38e1-4f10-8a12-6ea08d2a05f1
