### ISSUE TITLE
Selected State für Listen-Element

### ISSUE THREAD

**Issue by MadeleineMatter** [Lambda-IT/parlamentsdienste-components#151]
@thomasschneiter Aktualisierte Doku für das Listen-Element ist hier
https://xd.adobe.com/view/4b788182-140b-46ff-46f5-3c623cf5b5b3-3d49/screen/b7a08caf-a919-41a5-8d18-a81287ddbc8d

**Comment by CuriaPLUS** [comment]
Are there any updates?
The list item's hover colour is still #E3E0E0 but should be #DEE2E6 (Gray 3).

**Comment by thomasschneiter** [comment]
@CuriaPLUS hover color will be changed to "Gray 3" in v2.3.2. Is there anything else that need to be changed?

**Comment by CuriaPLUS** [comment]
No that's it. Thank you.
