### ISSUE TITLE
Storybook missing some controls

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#163]
There are some controls missing in the storybook and sometimes also the properties are not complete. 
It would be nice if we can see all properties and controls for every component
For example the panel has no controls
![image](https://user-images.githubusercontent.com/77280472/177280193-9ac37695-f5cb-421e-9752-9c43c1b4a3bf.png)

**Comment by tom-wenger** [comment]
The controls for pd-panel and pd-slider are now all in the storybook.
