### ISSUE TITLE
PdTable missing readonly/disabled state

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#168]
We miss a readonly or disabled state for the PdTable Component. 

The selectable state is unfortunately not enough since we can't display selected items when we disable that.

Is there a way to display the table in readonly mode while show the user which items are selected?

**Comment by thomasschneiter** [comment]
There is currently no way to show the selection checkboxes in a readonly mode.
Should the readonly mode only affect the selection checkboxes?
