### ISSUE TITLE
PdPanel collapse / pd-collapsed

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#171]
When using collapse=someBoolean and also using @pd-collapsed to do something if the panel is expanded the state of the collapse gets out of sync

Example: 
```
<pd-panel
        :collapsed="collapsed1"
        @pd-collapsed="handleCollapse($event, collapsed1)"
>

<pd-panel
        :collapsed="collapsed2"
        @pd-collapsed="handleCollapse($event, collapsed2)"
>

handleCollapse({detail: {collapsed}}, panel) {
   if (!collapsed) {
      if (collapsed1 === panel {
         collapsed2 = true
      } else collapsed1 = true
   }
}
```

What we try to do is close other panels if a panel is expanded but the state gets out of sync

**Comment by thomasschneiter** [comment]
I think the problem is that you create a 'loop' here. If you change the property `collapsed` a new event `pd-collapsed` is emitted which triggers another handleCollapse event.

If both panels change each other this wont work.

**Comment by CuriaPLUS** [comment]
I will try to add a better example today or next Week. It should work as I am only changing the other if it wasnt collapsed but let me make a working example and a video

**Comment by CuriaPLUS** [comment]
I made a video showing the behaviour it works correctly but the state of the other panel is wrong afterwards. If i click it twice its back to normal

https://user-images.githubusercontent.com/77280472/188110195-e18ee3ec-380b-4bcf-b3b6-67fcdfff5984.mov

**Comment by CuriaPLUS** [comment]
Looking at the panel-header code it could be that the state of the panel is not passed to the header correctly. It looks like the header reads the panel state on load but is not updated afterwards if the state is changed by something else then the header itself

**Comment by thomasschneiter** [comment]
I've fixed 2 issues with the collapsed state in pd-panel. Can you check if this now works for you?

**Comment by CuriaPLUS** [comment]
Looks good!
