### ISSUE TITLE
PD-List and List-Items

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#200]
We found a couple things with the lists

- [x] Hover effects only work for pd-list-item-expandable if content-click is enabled. We think this should be possible on the normal pd-list-item as well
- [x] Same with Panels sometimes we have to nest pd-lists and it would be nice to be able to also set the pd-list-padding somehow (same with panel and the --pd-panel-content-padding var)
- [x] content-click in nested lists are currently bubbling up to the highest possible handler maybe this is not the best default? We are stopping the propagation manually but maybe something to discuss

We were able to "fix" the paddings with a css hack but would be nice to be able to not use negative margins :)

**Comment by tom-wenger** [comment]
The padding for pd-list has already a --pd-list-content-padding variable who can be set.
