### ISSUE TITLE
PdTextArea

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#216]
This is rather hard to explain. We have a pd-textarea inside a pd-list-item-expandable, the panel goes from a col-3 to a col-12 size at the same time the pd-list-item-expandable is expanded.

As a result the pd-textarea is rendered and runAutoGrow is triggered. The issue now is that the maximise was still in progress -> the textarea calculates its height based on the initial value instead of the new much bigger space it would have. As a result the textarea has a lot of whitespace at the end.

I am not sure how to fix this as it is a combination of our and your functionality.

This is not an urgent Issue :)

**Comment by tom-wenger** [comment]
while disscussing this issue we were not quite shure how to reproduce this behaviour and how the exact situation is.
A screenshot would be helpful. Or the best would be a short screen-video!

**Comment by CuriaPLUS** [comment]
I will add a video the next time I see this issue, cannot reproduce it right now and this is not really urgent either. We can also just close this if you want
