### ISSUE TITLE
Datepicker Issue mit Input 

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#224]
**Description:**

Wenn ein Wert beim Datepicker eingegeben ist und man diesen löscht (Input Feld alles Löschen) mittels Klick ausserhalb des Feldes, wird der Wert nicht aktualisiert. Damit dieser aktualisiert wird muss man mit Tab oder mit Enter die (leere) Eingabe bestätigen. 

**Technisch**
Keines der Events wird konsistent getriggered wenn der User das Input Feld blurred -> wenn der Input geleert wird wird das nicht weiter geleitet 
pd-blur Event oder so würde das meiste glaub lösen aber muss analysiert werden

Für den User ist kein Unterschied erkennbar:

- Speichern möglich
- Feld wird wieder im initial/empty state dargestellt

Nach einem Refresh der Seite wird erst wieder der alte bzw. doch nicht überschriebene Wert dargestellt. 

Der Bug ist bereits bekannt und folgende Tickets existieren dazu:

- Lambda: https://github.com/Lambda-IT/parlamentsdienste-components/issues/123
- Flatpickr: https://github.com/flatpickr/flatpickr/issues/1551

Hint:
Bug wurde dokumentiert, muss aber via Lambda evaluiert werden.

**Comment by tom-wenger** [comment]
Is seems to be still an issue for flatpickr as well: https://github.com/carbon-design-system/carbon-components-svelte/issues/950
