### ISSUE TITLE
Flatpickr does not get removed from DOM when Datepicker is conditionally displayed

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#228]
If the datepicker component gets rendered conditionally by using a v-if or wrapped in a conditional component, everytime the component gets rendered a new Flatpickr  gets created but the old one never gets removed. Therefore the DOM gets bigger everytime a Datepicker gets rendered.

![image](https://user-images.githubusercontent.com/77280472/219030785-6e009b84-f451-48dc-af39-fda10ddd1c55.png)

**Comment by tom-wenger** [comment]
Ok, now we call a destroy-method for the flatpickr object in the disconnect-lifecycle of the component. if your re-rendering takes the components out of the DOM and puts it in again we think this will work.
This will be implemented in the next release and needs to be testet then.
