### ISSUE TITLE
Selection handling while filtering Pd-Table

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#242]
The combination of filtering and selection seems to no be in sync when you select more than 1 item.

How to reproduce:
- Filter for a key word
- Select 2 rows
- remove filter via clicking on the x icon

What happens:
More than just the selected rows are selected

What should happen:
Only the selected rows should be selected after removing the filter

https://user-images.githubusercontent.com/77280472/231716318-caee0bcd-a5d0-471c-9e58-0ca4f21ede85.mov

**Comment by tom-wenger** [comment]
We fixed this issue and released a new version.
Ready to test!

**Comment by CuriaPLUS** [comment]
Hey @tom-wenger and @thomasschneiter  ,

thank you for the fix. It seems like it fixed the original Issue, I could retest that. But it seems like that now the selection state seems to be not reseted correctly. I've recorded a video. Maybe you guys could take a look here and eventually reopen this issue.


https://user-images.githubusercontent.com/77280472/234623109-fd1d49d0-06e2-4b90-b280-a82a7f99105d.mov
