### ISSUE TITLE
Icons Typo

### ISSUE THREAD

**Issue by d3orn** [Lambda-IT/parlamentsdienste-components#248]
The drag&drop Icon has a typo "drap and drop" which shows up if the user hovers over the icon.

**Comment by tom-wenger** [comment]
Fixed in the latest release

**Comment by d3orn** [comment]
I think there are 2 drag_drop.svgs (once with Icon and once with icon) not sure why but it seems you fixed the wrong one

**Comment by tom-wenger** [comment]
It should be fixed now 👍
