### ISSUE TITLE
PdCombobox console.error

### ISSUE THREAD

**Issue by d3orn** [Lambda-IT/parlamentsdienste-components#249]
We are getting a lot of console.errors from pd-combobox on load 
![Screenshot 2023-05-30 at 17 08 08](https://github.com/Lambda-IT/parlamentsdienste-components/assets/411479/fdc6badb-001f-4333-a364-f504d1f88546)

I think there needs to be some checking if that this.state.items is not undefined
![Screenshot 2023-06-01 at 11 03 45](https://github.com/Lambda-IT/parlamentsdienste-components/assets/411479/582cb7cf-f247-46b9-b4f1-404a111eb1a7)

**Comment by tom-wenger** [comment]
We moved the initialization of the PdCombobox store into the constructor to prevent errors when new items are passed while the component is rendering. Please try it out and let me know if the issue is still there.
