### ISSUE TITLE
Breadcrumb vs Panel Padding

### ISSUE THREAD

**Issue by d3orn** [Lambda-IT/parlamentsdienste-components#251]
The breadcrumbs and panels are used on most pages and their padding is not the same leading to the Title not being aligned
![Screenshot 2023-06-12 at 08 13 44](https://github.com/Lambda-IT/parlamentsdienste-components/assets/411479/c4660e30-04d3-400d-bcfb-6dc651f5378c)

the breadcrumb has a left padding of 1rem whereas the panel has 1.25rem
I think 1rem is the preferred one, the panel content has 1.25rem as well - I think all the paddings (left:right) should be the same, either 1rem or 1.25rem

**Comment by tom-wenger** [comment]
I changed this and its released in v2.6.11

**Comment by d3orn** [comment]
The header is fine now but the panel-content padding is still to big.

**Comment by tom-wenger** [comment]
Sorry about the circumstances... i fixed it and released it again 👍
