### ISSUE TITLE
Css Issue in Storybook

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#252]
Hey,

I just want to inform you guys that there seems to be an Issue on your hosted Storybook.

<img width="1782" alt="image" src="https://github.com/Lambda-IT/parlamentsdienste-components/assets/77280472/e8ce4973-16b3-4c11-b188-f9ed9574c5e2">

Best Regards

**Comment by d3orn** [comment]
This is a bigger issue then expected as the library is broken as the image is never found

**Comment by tom-wenger** [comment]
so you have an error in the application? not just in the storybook? 
can you post an image of the error?

**Comment by d3orn** [comment]
Its the same error as above but I can post a screenshot later

**Comment by d3orn** [comment]
I did dig a bit deeper and I guess we just have to find all the usages of drap_drop on our side and change them as this is breaking if the old name is used

**Comment by d3orn** [comment]
But the error was/is the same as you have in your storybook

**Comment by d3orn** [comment]
I think you can close this
