### ISSUE TITLE
PdDatePicker Config

### ISSUE THREAD

**Issue by d3orn** [Lambda-IT/parlamentsdienste-components#256]
We sometimes use 2 Datepickers to select multiple Dates following each other and therefore have to update the minDate, maxDate or in general the config of a Datepicker depending on some user Input. Currently there is no watcher on the config prop which forces us to add a :key to force-rerender the whole datepicker.

This works for now but its a bad practise and would be nice to be done internally.

**Comment by tom-wenger** [comment]
I think this can be done with the set method the flatpicker provides.
`flatpicker.set('maxDate', '2023-8-15')`

**Comment by tom-wenger** [comment]
Can we close this?

**Comment by d3orn** [comment]
Sorry I haven't had time to look into your suggestion. I will get back to you this week

**Comment by d3orn** [comment]
Yes this can be closed!
