### ISSUE TITLE
PD-Timeline

### ISSUE THREAD

**Issue by d3orn** [Lambda-IT/parlamentsdienste-components#258]
I noticed a few things with <pd-timeline>:

- --pd-timeline-width: default should probably be auto instead of 300? This leads to the overflow as shown in the screenshot
- Furthermore the Dot of the timeline is neither horizontally nor vertically aligned :) (minor)
![Screenshot 2023-09-04 at 13 18 59](https://github.com/Lambda-IT/parlamentsdienste-components/assets/411479/37b3e308-3fa3-453e-91e7-e12ec0081941)

**Comment by tom-wenger** [comment]
i did set the --pd-timeline-width to auto and made some adjustments for a better alignment of the dot.
