### ISSUE TITLE
Icon_drag_drop

### ISSUE THREAD

**Issue by d3orn** [Lambda-IT/parlamentsdienste-components#259]
Maybe a merge gone wrong but Icon_drag_drop is with a capital I again making all the drag_drop icons fail :)

Did some more digging:

getURL(`./assets-icon/icon_${this.name}.svg`) in PdIcon.ts specifically checks for icon and not Icon I think this issue started when you removed the duplicated drag_drop.svg

You also change the complete svg-path of the drag_drop.svg making it bigger and offcentered

![Screenshot 2023-09-08 at 09 50 50](https://github.com/Lambda-IT/parlamentsdienste-components/assets/411479/d5809b53-cec4-41e9-a6e6-ea8dd0a259b7)

**Comment by tom-wenger** [comment]
Sorry i didn't see that capital i 🙈...
i uploaded the original file from the design system to have the origin path. let me know if there's still something wrong or can close this issue? (forever ;)
