### ISSUE TITLE
CSS Variable for padding on class pd-list-item-content and pd-list-item-expandable-content

### ISSUE THREAD

**Issue by vonmuehlenen** [Lambda-IT/parlamentsdienste-components#278]
Recently, we received the results of a UX review on our end, which indicated that the padding within the `pd-list-item` and `pd-list-item-expandable` is excessive.

![image](https://github.com/Lambda-IT/parlamentsdienste-components/assets/29423183/dba3734a-b924-4c12-afa7-062e9d2b22de)

Is it possible to add a CSS variable that we can use to adjust the size of the respective padding? This would apply to the pd-list-item-expandable component as well.

**Comment by tom-wenger** [comment]
there is a css-property --pd-list-content-padding on the pd-list component with which you can set the padding of the content. Maybe this is what you are looking for?

**Comment by vonmuehlenen** [comment]
Thanks for your response! We noticed that you have the option to change the `Pd-List` padding with that CSS variable. The wish would be to change the padding on the `pd-list-item-content` class and the matching class from the `pd-list-item-expandable`.

```
.pd-list-item-content {
    padding: 0.75rem; <--- 
    flex: 1 1 auto;
}
```

**Comment by tom-wenger** [comment]
yes, i see! i added a `--pd-list-item-padding` css variable with which you can control the padding of the items in the `pd-list-item` and the `pd-list-item-expandable`. 
As you write the padding of the pd-list-item was exessive, do you have a new (better) default value for it? now it was 0.75rem.
for the expandable-item we leave the default as it is?

**Comment by vonmuehlenen** [comment]
We discussed in the team, and you can leave the default as it is on both components. As long as we have the option to change the values with the CSS variable, it is fine.

**Comment by tom-wenger** [comment]
Ready to test in 3.0.4 👍
