### ISSUE TITLE
Pagination: Startpage and Max-Page Actions disabled

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#279]
**Actual:**

If the user is on the startpage or max-page (pagination available), all icons are still available. reload is executed, even if the user ist allready on the first or last page form the pagination. 

**Expected behavior:**

If the user ist on: 

- Startpage within a pagination, both arrows on the left side are disabled
- max-page within a pagination, both arrows to the right side are disabled

![image](https://github.com/Lambda-IT/parlamentsdienste-components/assets/77280472/3cbfc092-c04d-4368-819e-515a5530e598)

Danke und liebe Grüsse Eva

**Comment by tom-wenger** [comment]
Ready to test in v3.0.8
