### ISSUE TITLE
Request for a "clear" icon for the datepicker component

### ISSUE THREAD

**Issue by vonmuehlenen** [Lambda-IT/parlamentsdienste-components#293]
Currently, we have our own implementation where we add a button to clear the input of the date picker. The wish would be to have one directly inside the date picker, like the pd-combobox component, where you have the option to clear the input after a selection has been made. 

The icon should be toggleable with a prop like `show-clear-icon` or a similar option.

![image](https://github.com/Lambda-IT/parlamentsdienste-components/assets/29423183/04da4332-440d-44b4-a3a1-bd5a2c18db65)

Above is the example from your storybook for the `pd-combobox` component.

**Comment by tom-wenger** [comment]
@MadeleineMatter could you please make a design for this?

**Comment by tom-wenger** [comment]
ready to test
