### ISSUE TITLE
Keepalive datepicker issue

### ISSUE THREAD

**Issue by vonmuehlenen** [Lambda-IT/parlamentsdienste-components#294]
Currently, we have our filters wrapped inside a Vue built-in component named `keep-alive`. This is done to persist the filter state across a page transition. Upon page load, we can easily modify the filters, and the Flatpickr overlay is visible, allowing us to change our dates. After a date is chosen and we transition to another page, and then return to our page that holds our filters, the datepicker is broken. This means the overlay doesn't open anymore, and therefore, we do not have the chance to change the dates.

You both should have been added to a GitHub repository where you can easily reproduce the described issue. If you have any more questions, just contact either me or Domi. 

Vue.js Keepalive 
https://vuejs.org/guide/built-ins/keep-alive

**Comment by tom-wenger** [comment]
ready to test
