### ISSUE TITLE
table rows (content) wrong background colour

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#45]
According to the [XD Styleguide](https://xd.adobe.com/view/727dd55b-1491-4151-8f5d-db8600161be8-272e/screen/822f13fc-c5a9-4c0a-b1e6-ad8f4cc5a388/specs/) background-colour of table content rows should be white` #FFFFFF` not transparent.

**Comment by edispring** [comment]
@CuriaPLUS  It is more flexible if you set a background color #FFFFFF for the table instead.
