### ISSUE TITLE
Menu Component Placeholder/Text

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#46]
We have the requirement to allow a short text beneath the Menu Icon

![image-1](https://user-images.githubusercontent.com/77280472/116566186-d4cc7880-a906-11eb-962c-0c2a69c1cdb5.png)

We tried with the `:placeholder.prop` but this had no effect.

https://parlamentsdienstecore.lambda-it.ch/?path=/story/layout--menu

Is this possible with this component already?

Also here: https://xd.adobe.com/view/727dd55b-1491-4151-8f5d-db8600161be8-272e/screen/08bb52a8-fc0f-492c-9528-6445ecb33b7d/specs/

**Comment by edispring** [comment]
The label for the Menu Icon like "Aktionen" is missing.
