### ISSUE TITLE
Component Library Version 1.5.0 missing in package.json

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#48]
It seems that on version 1.5.0 was not set in the package.json, could you please update the file?
https://github.com/Lambda-IT/parlamentsdienste-components/tree/v1.5.0 

We have a CI Pipeline for this on our side which will break in such cases. 
As an alternative would it be possible that the Library is build and provided packaged on your side e.g. https://github.com/features/packages ?

**Comment by matthiasbaldi** [comment]
Oh yes. I forgot that. May we could publish a tar.gz in the Release?
Then we do not have to configure the repository for that.

**Comment by thomasschneiter** [comment]
fixed with v1.5.1 release https://github.com/Lambda-IT/parlamentsdienste-components/releases/tag/v1.5.1

**Comment by matthiasbaldi** [comment]
@CuriaPLUS fyi we will prepare a build process over Github Actions to deploy a npm package for every release.
