### ISSUE TITLE
PD-Table iconConfig

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#49]
Ok the iconConfig for rows works but not as intended. 
If the PdTable.iconConfig has values set to true, they cannot be overwritten by the row.iconConfig
also leaving the PdTable.iconConfig empty (set all values to false) but setting the Icons in row.iconConfig makes the icons overlay the row left to the icons (see Screenshot)

<img width="362" alt="Screenshot 2021-05-03 at 15 42 48" src="https://user-images.githubusercontent.com/77280472/116883781-43bb1180-ac26-11eb-9d9c-ca575e105559.png">

**Comment by CuriaPLUS** [comment]
Furthermore we saw in one of the release notes that the ActionMenu is now supported. Could you update the docu to include this feature? How do we set the Items and what actions are called, preferably in the VueJS context

**Comment by matthiasbaldi** [comment]
The action menu is supported since the [Release 1.2.0](https://github.com/Lambda-IT/parlamentsdienste-components/releases/tag/v1.2.0).
We add in the next release (5.1.2) some new features that you also can add a menu label.
The documentation is here: https://parlamentsdienstecore.lambda-it.ch/?path=/story/interactions-table--table

**Comment by CuriaPLUS** [comment]
The menu prop seems to be missing/not working with the current version. We tried a few different options: 
```
:menus.prop="menu"
:menu.prop="menu"
:menu="menu"
```
Looking at the code it seems like @Prop() for menu is missing?

**Comment by matthiasbaldi** [comment]
I know now what you mean. This bug will also be closed in 1.5.2
- iconConfig in #47 
- table menu label will be closed in issue/pr #51

**Comment by CuriaPLUS** [comment]
Could you elaborate? I can now set the menuLabel but not the menu options:
```
menu: [
        { text: 'Drucken', icon: 'print' },
        { text: 'Contact', icon: 'contact' },
],
```
with VueJS

```
<pd-table
  :menuLabel.prop="'Test'"
  :menu.prop="menu"
></pd-table>
```

**Comment by matthiasbaldi** [comment]
Did you tried the following example?

```html
<pd-menu>
    <pd-menu-item text="Print" @click="printIt()">
        <pd-icon size="2" name="print"></pd-icon>
    </pd-menu-item>
</pd-menu>
```
You can also see here: https://parlamentsdienstecore.lambda-it.ch/?path=/story/layout--menu

The buttons/links for the menu is not a property to configure.
We implemented them as childs - for the StencilJS-component as a slot.

Was this helpful? I think you tried to set it as property/html attribute.
