### ISSUE TITLE
Event / Focus issue with pd-table and pd-combobox

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#59]
We currently have an issue with two components reacting to one another. Specifically we have a pd-table with a delete icon per row and a pd-combobox above. When deleting a table entry int the pd-table, the pd-combobox is suddenly displayed as "open"

![image-2021-06-03-14-35-48-699](https://user-images.githubusercontent.com/77280472/124426431-52c75880-dd6a-11eb-8773-556527c98476.png)

What could trigger such a behaviour? We checked for events but could not find any triggering this. Focus should not trigger the drop down to open as far as we saw.

**Comment by thomasschneiter** [comment]
@CuriaPLUS I've found an issue where the combobox opens when the items change. I assume in your case the items in the combobox changed when a row was deleted.

The issue is fixed with release 1.6.2

**Comment by CuriaPLUS** [comment]
We will update and verify asap. Thank you!

**Comment by CuriaPLUS** [comment]
Works fine thank you for the fix
