### ISSUE TITLE
PD-Button icon-only

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#67]
It is currently not possible to have a button that only has an Icon but no Text. If the text is left out the icon always either has a margin-left or margin-right. Not setting the icon-location leads to a not rendered icon all together

**Comment by thomasschneiter** [comment]
I've added a 'center' position for icon only buttons. You can additionally use css vars to modify paddings/radius of the button if needed.
`--pd-button-left-radius`       
`--pd-button-right-radius`      
`--pd-button-padding-vertical`  
`--pd-button-padding-horizontal`
