### ISSUE TITLE
Paggination and Table

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#69]
As we initially discussed Pagination is handled by us and PD-Table is responsible for rendering the Data.
This leads to multiple Issues to explain those I will try to explain how the Pagination is handled:
- We get an array of data
- Depending on the Users settings we create slices with the defined number of entries (for example 25 entries per page)
- We tell PD-Table to render the currently active slices (page 1 for example)
- If the user goes to the next page -> we change the data passed to PD-Table to render the new page

There are a few drawbacks with this approach:

1. The orderBy function of each table column only works on the current slice/page -> if the user moves to the next page the state of the table is still showing the arrow for the selected column but the data is not ordered anymore. Furthermore as the table only has 1 page we cannot order all the data before creating the slices leading to a ordered first page but to unordered pages after that.
2. Similar to that the filtering also only works on the current slice resulting in fewer than selected entries per page 

There are two approaches to fix this
Either the pagination is handled by the table, passing in number of items per page, the complete list of all data, handlers for next/previous/last/first page. This would make the table usable without much heavy lifting from us or future implementors of the library

Or PD-Table would need to provide callback for filter and order events with the given row, asc/desc and the submitted value for filtering 
-> the heavy lifting is done by whoever implements the library

**Comment by matthiasbaldi** [comment]
Must be discussed mid-August.

**Comment by CuriaPLUS** [comment]
Can we setup a Meeting for this Topic?

**Comment by thomasschneiter** [comment]
@CuriaPLUS I've create a [1.8.0-1 pre-release](https://github.com/Lambda-IT/parlamentsdienste-components/releases/tag/v1.8.0-1) that contains paging for pd-table. Can you give us a feedback if this satisfies your requirements?

**Comment by CuriaPLUS** [comment]
Feedback:

Does work:
- Sorting over all data
- Filtering over all data
- Selecting over all data
- pageSizes

Does not work:
- pagination => prev - next
- Total pages show 0
- Styling: It would be nice if the pagination is after the table, not inside the table
- Reactivity of data list

**Comment by thomasschneiter** [comment]
@CuriaPLUS Can you compare your solution to the [Storybook example](https://parlamentsdienstecore.app.lambda-it.ch/?path=/story/interactions-table--table)? Pagination / Styling / Reactivity works there and I'm not really sure what to fix. The example is [this Story here](https://github.com/Lambda-IT/parlamentsdienste-components/blob/master/src/components/pd-table/pd-table.stories.js) maybe you can find what's different.

**Comment by thomasschneiter** [comment]
@CuriaPLUS I've updated the pd-table in v2.1.0

Currently I have the problem, that It's not clear how the table should behave on new 'rows' data. There are basically two options.

1. completely new data for all rows.
2. a single row was edit/removed.

If only one row was updated, I assume that the the current page should stay the same. 
But if multiple rows change, the table should probably completely refresh.

This is why i changed 2 things: 
- Changing `rows` should now update the selectAll checkbox, filter, sort and totalPages. Also if you're for example on page "4 of 4" and the new data contains only 3 pages the current page is updated to "3 of 3".
- Added a Method to manually reset the table if new data was added.

Do you see other options that should be added?
