### ISSUE TITLE
pd-icon generates an error

### ISSUE THREAD

**Issue by jwanner83** [Lambda-IT/parlamentsdienste-components#72]
Hello guys, 
we are currently implementing your library into our existing project for the Parlamentsdienste. We run into a problem with the `pd-icon` component. It doesn't display the icon correctly and throws an error. 

Please have a look at this repository: https://github.com/jwanner83/pd-components-library-icons-issue It contains a minimal Vue 2 project which should display a cancel button but instead throws an error.

Am I missing out on something, or am I doing something wrong? If I try to use a different component, like the pd-input one, it works just fine.

Thank you in advance for your help.

Best regards, Jonas

**Comment by jwanner83** [comment]
Additional information: I use the library in the version 1.7.1 through npm .

**Comment by jwanner83** [comment]
I've stumbled upon the https://github.com/Lambda-IT/parlamentsdienste-components/issues/2 issue, which describes the same issue I have here. I managed to fix it with the meta tag solution. 

I highly suggest adding this to the documentation.

**Comment by matthiasbaldi** [comment]
Ok @jwanner83. Then I will reopen the issue to fix this in the documentation. 👍 
Thank you for your feedback.

- [ ] Improve documentation

**Comment by jwanner83** [comment]
As a small side note, as I'm already on the topic of icons: The `Icon_drag_drop.svg` icon is written with an uppercase I, although all others are written in lowercase letters. This causes as well an error on the storybook page which you can find here: https://parlamentsdienstecore.lambda-it.ch/?path=/story/typography-icon--basic

@matthiasbaldi no problem 👍
