### ISSUE TITLE
PD-Table actions

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#77]
The icons for actions inside a table (... - Menu, Top Right of the Table, see example) sometimes are not rendered if the table is re-rendered

```
<pd-table
      header-style="gray"
      :rows.prop="rows"
      :columns.prop="columns"
      :iconConfig.prop="iconConfig"
      :showActionColumn.prop="true"
      @pd-view="viewPerson"
      @pd-edit="editPerson"
      @pd-delete="deletePerson"
      @pd-clicked-row="viewPerson"
      :selectable="true"
    >
      <pd-menu-item
        :text="$t('global.action_menu.xls')"
        @click="requestsXLSExport"
      >
        <pd-icon name="link" size="2" />
      </pd-menu-item>
</pd-table>
```

Screenshots:
![Screenshot 2021-09-08 at 09 48 23](https://user-images.githubusercontent.com/77280472/132468525-04fa740f-b926-4fa7-a268-d2dfe52517c4.png)

![Screenshot 2021-09-08 at 09 48 29](https://user-images.githubusercontent.com/77280472/132468522-8fd4d3f2-a598-4ec0-8453-206443f2a46c.png)

**Comment by matthiasbaldi** [comment]
We analyzed the IntersectionObserver for any issues but we were not able to find something.
But to bring you a solution we implemented a `lazy` attribute which is default on true.
With this attribute you can try to set the icons in the menu entries to `lazy="no"` and give us feedback if it solves the issue.

This will be released today.
