### ISSUE TITLE
PD-Chip & VueJS 3

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#78]
We are upgrading to VueJS 3 and noticed that pd-chip removeChip event is not properly triggered, @click works fine and the custom events for other Elements like Combobox and so on usually worked without issue.

Did some digging and found how to fix this:
``` 
    this.removeChip = index.createEvent(this, "removeChip", 7);
    this.checkChip = index.createEvent(this, "checkChip", 7);
``` 

should be changed to

```
    this.removeChip = index.createEvent(this, "remove-chip", 7);
    this.checkChip = index.createEvent(this, "check-chip", 7);
```

Also for consistency I suggest to change the name of those events to pd-remove-chip and pd-check-chip

**Comment by matthiasbaldi** [comment]
Thank you for the feedback. Indeed here an overwritten event name was not set properly.
