### ISSUE TITLE
PD-Combobox error

### ISSUE THREAD

**Issue by CuriaPLUS** [Lambda-IT/parlamentsdienste-components#83]
PD-Combobox has an error if the list is an empty array
-> Cannot read properties of undefined (reading 'label')

r.selectItem is called on first render as well as the callbacks are triggered (pd-combobox and pd-change)

**Comment by matthiasbaldi** [comment]
thank you. I will analyze that. 
Do you use the latest release -> v1.7.3?

**Comment by CuriaPLUS** [comment]
Yes we updated to 1.7.3 yesterday

**Comment by matthiasbaldi** [comment]
Fix should be available on Version 1.7.4
https://github.com/Lambda-IT/parlamentsdienste-components/packages/785775?version=1.7.4
